name: 'Jest badges generation action'
description: 'Action generating jest coverage badges and pushing them to the repo'

inputs:
  branches:
    description: 'Branches on which the badges should be generated. Commas separated.'
    default: 'master'
  workingDir:
    description: 'Working dir for the job'
    default: '.'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: check-square
  color: green
